package com.arkeomag.pro;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.media.*;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;

public class MainActivity extends Activity implements SensorEngine.Listener{
 int BG=Color.rgb(5,10,20),CARD=Color.rgb(13,25,43),CYAN=Color.rgb(0,210,255),WARN=Color.rgb(255,190,0),RED=Color.rgb(255,40,60); SensorEngine se; LinearLayout root,content,nav; TextView status; GraphView graph; BarGraphView bars; HeatmapView heat; RadarView radar; Surface3DView surface; FourDView fourd; CalibrationPanel cal; float delta; ToneGenerator tone;
 public void onCreate(Bundle b){super.onCreate(b);tone=new ToneGenerator(AudioManager.STREAM_MUSIC,70);se=new SensorEngine(this);se.add(this);buildBase();showHome();se.start();}
 public void onDestroy(){super.onDestroy();se.stop();}
 TextView tv(String s,int sp,int c,int style){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);v.setTypeface(Typeface.DEFAULT,style);v.setPadding(12,8,12,8);return v;} GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);g.setStroke(1,Color.argb(60,255,255,255));return g;}
 void buildBase(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(14,14,14,8);root.setBackgroundColor(BG);status=tv("ArkeoMag Pro Video Edition",20,Color.WHITE,Typeface.BOLD);root.addView(status,new LinearLayout.LayoutParams(-1,-2));content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);ScrollView sv=new ScrollView(this);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);root.addView(nav,new LinearLayout.LayoutParams(-1,60));setContentView(root);}
 void clear(String title){status.setText(title+"  |  X "+fmt(se.x)+" Y "+fmt(se.y)+" Z "+fmt(se.z)+" |B| "+fmt(se.total)+" Δ "+fmt(se.anomaly));content.removeAllViews();nav.removeAllViews();String[] n={"Ana","Ded.","Kal.","Grid","Sonar","3D","4D"};Runnable[] r={()->showHome(),()->showDetector(),()->showCal(),()->showGrid(),()->showRadar(),()->show3D(),()->show4D()};for(int i=0;i<n.length;i++){Button b=new Button(this);b.setText(n[i]);final int k=i;b.setOnClickListener(v->r[k].run());nav.addView(b,new LinearLayout.LayoutParams(0,-1,1));}}
 Button card(String title,String sub,Runnable r){Button b=new Button(this);b.setAllCaps(false);b.setText(title+"\n"+sub);b.setTextSize(17);b.setTextColor(Color.WHITE);b.setBackground(bg(CARD,24));b.setOnClickListener(v->r.run());b.setPadding(12,18,12,18);return b;}
 void showHome(){clear("Ana Menü");GridLayout grid=new GridLayout(this);grid.setColumnCount(2);content.addView(grid);String[][] items={{"DEDEKTÖR","Canlı manyetik sinyal"},{"KALİBRASYON","XY / YZ / XZ daireleri"},{"YÜZEY TARAMA","Grid + heatmap"},{"SONAR RADAR","360° sweep"},{"3D SURFACE","Renkli yüzey modeli"},{"4D SURFACE","Zamanlı 3D akış"},{"CSV / BT","Kayıt ve cihaz"}};Runnable[] rr={()->showDetector(),()->showCal(),()->showGrid(),()->showRadar(),()->show3D(),()->show4D(),()->showTools()};for(int i=0;i<items.length;i++){GridLayout.LayoutParams lp=new GridLayout.LayoutParams();lp.width=getResources().getDisplayMetrics().widthPixels/2-28;lp.height=155;lp.setMargins(6,8,6,8);grid.addView(card(items[i][0],items[i][1],rr[i]),lp);}}
 void showDetector(){clear("Dedektör");content.addView(tv("TARGET SCORE / ANOMALY",16,CYAN,Typeface.BOLD));GaugeView gauge=new GaugeView(this);content.addView(gauge,new LinearLayout.LayoutParams(-1,250));graph=new GraphView(this);content.addView(graph,new LinearLayout.LayoutParams(-1,210));bars=new BarGraphView(this);content.addView(bars,new LinearLayout.LayoutParams(-1,180));Button c=card("TABAN DEĞERİ SIFIRLA","Kalibrasyon referansı al",()->se.calibrate());content.addView(c,new LinearLayout.LayoutParams(-1,115));}
 void showCal(){clear("Kalibrasyon");content.addView(tv("Telefonu 8 çizerek döndür. XY / YZ / XZ noktaları merkeze yaklaştıkça kalibrasyon iyileşir.",15,Color.LTGRAY,Typeface.NORMAL));cal=new CalibrationPanel(this);content.addView(cal,new LinearLayout.LayoutParams(-1,360));content.addView(card("BİTİR VE KAYDET","Mevcut |B| taban alınır",()->se.calibrate()),new LinearLayout.LayoutParams(-1,115));}
 void showGrid(){clear("Yüzey Tarama - Heatmap");content.addView(tv("Nokta topla: her sensör örneği grid üzerinde renkli yoğunluk üretir.",15,Color.LTGRAY,Typeface.NORMAL));heat=new HeatmapView(this);content.addView(heat,new LinearLayout.LayoutParams(-1,520));content.addView(card("GRID TEMİZLE","Yeni tarama başlat",()->{heat.pts.clear();heat.invalidate();}),new LinearLayout.LayoutParams(-1,105));}
 void showRadar(){clear("Sonar Radar");radar=new RadarView(this);content.addView(radar,new LinearLayout.LayoutParams(-1,560));content.addView(tv("Yeşil kol canlı sweep, sarı noktalar güçlü anomalileri temsil eder.",15,Color.LTGRAY,Typeface.NORMAL));}
 
 void show4D(){clear("4D Surface Time Scan");fourd=new FourDView(this);content.addView(fourd,new LinearLayout.LayoutParams(-1,620));content.addView(tv("4D = 3D yüzey + zaman akışı. Sensör anomalileri frame olarak işlenir.",15,Color.LTGRAY,Typeface.NORMAL));}
void show3D(){clear("3D Surface");surface=new Surface3DView(this);content.addView(surface,new LinearLayout.LayoutParams(-1,610));content.addView(tv("2D grid verisi IDW/Kriging tarzı enterpolasyon ile 3D yüzeye aktarılır.",15,Color.LTGRAY,Typeface.NORMAL));}
 void showTools(){clear("CSV / Bluetooth");content.addView(tv("CSV export ve Bluetooth protokol modülü için temel ekran. Harici cihaz protokolü sonraki aşamada eşleştirilir.",16,Color.WHITE,Typeface.NORMAL));content.addView(card("CSV DIŞA AKTAR","timestamp,x,y,z,total,anomaly",()->saveCsv()),new LinearLayout.LayoutParams(-1,120));content.addView(card("BLUETOOTH TARA","Android izinleri sonrası cihaz listesi",()->Toast.makeText(this,"Bluetooth tarama modülü hazır",0).show()),new LinearLayout.LayoutParams(-1,120));}
 void saveCsv(){try{File f=new File(getExternalFilesDir(null),"arkeomag_scan.csv");FileWriter fw=new FileWriter(f,true);fw.write(System.currentTimeMillis()+","+se.x+","+se.y+","+se.z+","+se.total+","+se.anomaly+"\n");fw.close();Toast.makeText(this,"Kaydedildi: "+f.getName(),0).show();}catch(Exception e){Toast.makeText(this,e.toString(),1).show();}}
 public void onSensor(float x,float y,float z,float total,float anomaly,float tilt){delta=anomaly;status.setText("ArkeoMag Pro  |  X "+fmt(x)+" Y "+fmt(y)+" Z "+fmt(z)+" |B| "+fmt(total)+" Δ "+fmt(anomaly));if(graph!=null)graph.add(total, anomaly);if(bars!=null)bars.set(x,y,z);if(heat!=null)heat.addPoint(anomaly);if(radar!=null)radar.update(anomaly);if(surface!=null)surface.add(anomaly);if(fourd!=null)fourd.add(anomaly);if(cal!=null)cal.set(x,y,z);if(anomaly>25)tone.startTone(ToneGenerator.TONE_PROP_BEEP,70);} String fmt(float v){return String.format(Locale.US,"%.1f",v);} 
 public class GaugeView extends View{Paint p=new Paint(1);public GaugeView(Context c){super(c);}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();p.setStrokeWidth(25);p.setStyle(Paint.Style.STROKE);p.setColor(Color.DKGRAY);c.drawArc(70,45,w-70,h*2-80,200,140,false,p);p.setColor(delta>25?RED:delta>12?WARN:CYAN);c.drawArc(70,45,w-70,h*2-80,200,Math.min(140,delta*4),false,p);p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);p.setColor(Color.WHITE);p.setTextSize(52);c.drawText(fmt(delta)+" µT",w/2,h/2,p);p.setTextSize(25);p.setColor(Color.LTGRAY);c.drawText(delta>25?"GÜÇLÜ HEDEF":delta>12?"ORTA ANOMALİ":"NORMAL",w/2,h/2+46,p);invalidate();}}
}
