package com.arkeomag.pro;

import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;
import android.graphics.drawable.GradientDrawable;import android.hardware.*;import android.media.*;import android.opengl.*;import android.view.*;import android.widget.*;import java.nio.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity implements SensorEventListener{
    SensorManager sm; Sensor mag,acc,gyro; float[] m={0,0,0}, a={0,0,0}, g={0,0,0}, base={0,0,0}; boolean hasBase=false; double total=0,delta=0; LinearLayout root,content,bottom; TextView title,subtitle,readout; ArrayList<Float> history=new ArrayList<>(); int screen=0; ToneGenerator tone; long lastBeep=0;
    final int BG=Color.rgb(7,17,31), CARD=Color.rgb(14,32,54), CYAN=Color.rgb(45,212,191), BLUE=Color.rgb(59,130,246), WARN=Color.rgb(251,191,36), RED=Color.rgb(248,113,113);
    public void onCreate(Bundle b){super.onCreate(b); if(Build.VERSION.SDK_INT>=23)requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.BLUETOOTH_SCAN,Manifest.permission.BLUETOOTH_CONNECT},5); tone=new ToneGenerator(AudioManager.STREAM_MUSIC,60); sm=(SensorManager)getSystemService(SENSOR_SERVICE); mag=sm.getDefaultSensor(Sensor.TYPE_MAGNETIC_FIELD); acc=sm.getDefaultSensor(Sensor.TYPE_ACCELEROMETER); gyro=sm.getDefaultSensor(Sensor.TYPE_GYROSCOPE); buildShell(); showMenu();}
    public void onResume(){super.onResume(); if(mag!=null)sm.registerListener(this,mag,SensorManager.SENSOR_DELAY_GAME); if(acc!=null)sm.registerListener(this,acc,SensorManager.SENSOR_DELAY_GAME); if(gyro!=null)sm.registerListener(this,gyro,SensorManager.SENSOR_DELAY_GAME);} public void onPause(){super.onPause();sm.unregisterListener(this);} 
    void buildShell(){LinearLayout main=new LinearLayout(this);main.setOrientation(LinearLayout.VERTICAL);main.setBackgroundColor(BG);setContentView(main); title=t("ArkeoMag Pro",24,Color.WHITE,true);title.setPadding(18,14,18,0);main.addView(title);subtitle=t("Sensör hazır • Login yok • v6 3D/Heatmap/Radar",12,Color.LTGRAY,false);subtitle.setPadding(18,0,18,8);main.addView(subtitle); readout=t("X 0  Y 0  Z 0   |B| 0 µT   Sapma 0 µT",12,CYAN,false);readout.setPadding(18,6,18,10);main.addView(readout); ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(14,8,14,8);sv.addView(content);main.addView(sv,new LinearLayout.LayoutParams(-1,0,1));bottom=new LinearLayout(this);bottom.setOrientation(LinearLayout.HORIZONTAL);bottom.setPadding(4,4,4,8);main.addView(bottom,new LinearLayout.LayoutParams(-1,70)); String[] ns={"Menü","Dedektör","Kalibrasyon","Area","Sonar","3D"}; for(int i=0;i<ns.length;i++){final int k=i;TextView bt=t(ns[i],11,Color.WHITE,false);bt.setGravity(Gravity.CENTER);bt.setBackground(round(CARD,18));bt.setOnClickListener(v->{ if(k==0)showMenu(); if(k==1)showDetector(); if(k==2)showCalibration(); if(k==3)showArea(); if(k==4)showSonar(); if(k==5)show3D();}); bottom.addView(bt,new LinearLayout.LayoutParams(0,-1,1));}}
    TextView t(String s,int sp,int c,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c); if(bold)v.setTypeface(Typeface.DEFAULT_BOLD);return v;} GradientDrawable round(int color,int r){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(r);d.setStroke(1,Color.argb(80,255,255,255));return d;}
    TextView card(String title,String sub,int accent){TextView v=t(title+"\n"+sub,18,Color.WHITE,true);v.setPadding(22,20,22,20);v.setBackground(round(CARD,26));v.setTextColor(Color.WHITE);return v;} void clear(String s){screen=0;content.removeAllViews();title.setText(s);} 
    public void showMenu(){clear("ArkeoMag Pro Classic"); String[][] cards={{"DEDEKTÖR","Canlı manyetik hedef göstergesi"},{"KALİBRASYON","XY / YZ / XZ taban ayarı"},{"LIVE SCAN","Yürüyüş izli canlı tarama"},{"AREA SCAN","Renkli grid heatmap"},{"SONAR / RADAR","360° radar sweep"},{"3D SURFACE","OpenGL yüzey + hedefler"},{"CSV KAYIT","Tarama verilerini dışa aktar"},{"BLUETOOTH","Harici cihaz bağlantı iskeleti"}}; for(String[] c:cards){TextView v=card(c[0],c[1],CYAN); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,150);lp.setMargins(0,0,0,14);content.addView(v,lp); if(c[0].startsWith("DED"))v.setOnClickListener(x->showDetector()); if(c[0].startsWith("KAL"))v.setOnClickListener(x->showCalibration()); if(c[0].startsWith("LIVE"))v.setOnClickListener(x->showLive()); if(c[0].startsWith("AREA"))v.setOnClickListener(x->showArea()); if(c[0].startsWith("SONAR"))v.setOnClickListener(x->showSonar()); if(c[0].startsWith("3D"))v.setOnClickListener(x->show3D()); }}
    public void showDetector(){clear("Dedektör"); screen=1; GaugeView gv=new GaugeView(this);content.addView(gv,new LinearLayout.LayoutParams(-1,360)); GraphView gr=new GraphView(this);content.addView(gr,new LinearLayout.LayoutParams(-1,260)); BarView bv=new BarView(this);content.addView(bv,new LinearLayout.LayoutParams(-1,190)); Button b=new Button(this);b.setText("Taban Değeri Sıfırla");b.setOnClickListener(v->{System.arraycopy(m,0,base,0,3);hasBase=true;});content.addView(b,new LinearLayout.LayoutParams(-1,110));}
    public void showCalibration(){clear("Kalibrasyon"); screen=2; content.addView(t("Telefonu 8 çizerek döndür. XY / YZ / XZ eksenlerini doldur.",16,Color.WHITE,false)); CalibView cv=new CalibView(this);content.addView(cv,new LinearLayout.LayoutParams(-1,520)); Button b=new Button(this);b.setText("Kalibrasyonu Kaydet");b.setOnClickListener(v->{System.arraycopy(m,0,base,0,3);hasBase=true;Toast.makeText(this,"Kalibrasyon kaydedildi",0).show();});content.addView(b,new LinearLayout.LayoutParams(-1,110));}
    public void showLive(){clear("Live Scan"); screen=3; content.addView(t("Canlı tarama izi: yürüdükçe anomali noktaları akar.",15,Color.LTGRAY,false)); LiveView lv=new LiveView(this);content.addView(lv,new LinearLayout.LayoutParams(-1,620));}
    public void showArea(){clear("Area Scan Heatmap"); screen=4; HeatMapView hv=new HeatMapView(this);content.addView(hv,new LinearLayout.LayoutParams(-1,700));}
    public void showSonar(){clear("Sonar Radar"); screen=5; RadarView rv=new RadarView(this);content.addView(rv,new LinearLayout.LayoutParams(-1,720));}
    public void show3D(){clear("3D Surface"); screen=6; GLSurface gl=new GLSurface(this);content.addView(gl,new LinearLayout.LayoutParams(-1,720)); content.addView(t("OpenGL yüzey: anomali gücüne göre hedefler yükselir.",14,Color.LTGRAY,false));}
    public void onSensorChanged(SensorEvent e){ if(e.sensor.getType()==Sensor.TYPE_MAGNETIC_FIELD)System.arraycopy(e.values,0,m,0,3); if(e.sensor.getType()==Sensor.TYPE_ACCELEROMETER)System.arraycopy(e.values,0,a,0,3); if(e.sensor.getType()==Sensor.TYPE_GYROSCOPE)System.arraycopy(e.values,0,g,0,3); total=Math.sqrt(m[0]*m[0]+m[1]*m[1]+m[2]*m[2]); if(!hasBase){System.arraycopy(m,0,base,0,3);hasBase=true;} float dx=m[0]-base[0],dy=m[1]-base[1],dz=m[2]-base[2]; delta=Math.sqrt(dx*dx+dy*dy+dz*dz); history.add((float)delta); if(history.size()>180)history.remove(0); readout.setText(String.format(Locale.US,"X %.1f  Y %.1f  Z %.1f   |B| %.1f µT   Sapma %.1f µT",m[0],m[1],m[2],total,delta)); if(delta>18 && System.currentTimeMillis()-lastBeep>350){lastBeep=System.currentTimeMillis();tone.startTone(ToneGenerator.TONE_PROP_BEEP,70);} content.invalidate();}
    public void onAccuracyChanged(Sensor s,int a){}
    class GaugeView extends View{Paint p=new Paint(1);GaugeView(Context c){super(c);}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();p.setStrokeWidth(26);p.setStyle(Paint.Style.STROKE);p.setColor(Color.DKGRAY);c.drawArc(80,50,w-80,h*2-80,200,140,false,p);p.setColor(delta>25?RED:delta>12?WARN:CYAN);c.drawArc(80,50,w-80,h*2-80,200,(float)Math.min(140,delta*4),false,p);p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(56);p.setColor(Color.WHITE);c.drawText(String.format(Locale.US,"%.1f µT",delta),w/2,h/2,p);p.setTextSize(24);p.setColor(Color.LTGRAY);c.drawText(delta>25?"GÜÇLÜ HEDEF":delta>12?"ORTA ANOMALİ":"NORMAL",w/2,h/2+48,p);invalidate();}}
    class GraphView extends View{Paint p=new Paint(1);GraphView(Context c){super(c);}protected void onDraw(Canvas c){p.setColor(CARD);c.drawRoundRect(0,0,getWidth(),getHeight(),26,26,p);p.setColor(CYAN);p.setStrokeWidth(4);Path path=new Path();for(int i=0;i<history.size();i++){float x=i*(getWidth()/(float)180);float y=getHeight()-20-Math.min(getHeight()-40,history.get(i)*7);if(i==0)path.moveTo(x,y);else path.lineTo(x,y);}c.drawPath(path,p);invalidate();}}
    class BarView extends View{Paint p=new Paint(1);BarView(Context c){super(c);}protected void onDraw(Canvas c){float[] vals={Math.abs(m[0]-base[0]),Math.abs(m[1]-base[1]),Math.abs(m[2]-base[2])};int w=getWidth()/3;String[] n={"X","Y","Z"};for(int i=0;i<3;i++){p.setColor(i==0?CYAN:i==1?BLUE:WARN);float bh=Math.min(getHeight()-50,vals[i]*8);c.drawRoundRect(i*w+25,getHeight()-25-bh,(i+1)*w-25,getHeight()-25,16,16,p);p.setColor(Color.WHITE);p.setTextSize(22);p.setTextAlign(Paint.Align.CENTER);c.drawText(n[i],i*w+w/2,25,p);}invalidate();}}
    class CalibView extends View{Paint p=new Paint(1);CalibView(Context c){super(c);}protected void onDraw(Canvas c){p.setColor(CARD);c.drawRoundRect(0,20,getWidth(),getHeight()-20,26,26,p);int cx=getWidth()/2;int cy=getHeight()/2;p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);p.setColor(Color.GRAY);c.drawCircle(cx,cy,180,p);c.drawCircle(cx,cy,110,p);p.setStyle(Paint.Style.FILL);p.setColor(CYAN);c.drawCircle(cx+m[0]*4,cy+m[1]*4,18,p);p.setTextSize(26);p.setColor(Color.WHITE);c.drawText("Kalite: "+(delta<8?"İyi":delta<18?"Orta":"Yüksek sapma"),30,60,p);invalidate();}}
    class LiveView extends View{Paint p=new Paint(1);Random r=new Random();LiveView(Context c){super(c);}protected void onDraw(Canvas c){p.setColor(CARD);c.drawRoundRect(0,0,getWidth(),getHeight(),28,28,p);int n=history.size();for(int i=0;i<n;i++){float v=history.get(i);p.setColor(v>25?RED:v>12?WARN:CYAN);float x=(i%30)*(getWidth()/30f)+16;float y=(i/30)*(getHeight()/8f)+35;c.drawCircle(x,y,8+Math.min(20,v/2),p);}invalidate();}}
    class HeatMapView extends View{Paint p=new Paint(1);HeatMapView(Context c){super(c);}protected void onDraw(Canvas c){int cols=10,rows=12;float cw=getWidth()/cols,ch=getHeight()/rows;for(int y=0;y<rows;y++)for(int x=0;x<cols;x++){float d=(float)(Math.abs(Math.sin((x+y+history.size())*.33))*delta + Math.random()*3);p.setColor(d>25?RED:d>14?WARN:d>7?Color.rgb(34,197,94):BLUE);c.drawRect(x*cw+3,y*ch+3,(x+1)*cw-3,(y+1)*ch-3,p);}invalidate();}}
    class RadarView extends View{Paint p=new Paint(1);float ang=0;RadarView(Context c){super(c);}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight(),cx=w/2,cy=h/2;int R=Math.min(w,h)/2-30;p.setColor(Color.rgb(3,12,24));c.drawCircle(cx,cy,R+20,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);p.setColor(Color.argb(140,45,212,191));for(int i=1;i<=4;i++)c.drawCircle(cx,cy,R*i/4,p);c.drawLine(cx-R,cy,cx+R,cy,p);c.drawLine(cx,cy-R,cx,cy+R,p);p.setStyle(Paint.Style.FILL);ang+=3;double a=Math.toRadians(ang);p.setColor(Color.argb(180,45,212,191));c.drawLine(cx,cy,cx+(float)Math.cos(a)*R,cy+(float)Math.sin(a)*R,p);for(int i=0;i<history.size();i+=20){float v=history.get(i);double aa=Math.toRadians((i*19)%360);float rr=(float)Math.min(R-20,40+v*7);p.setColor(v>20?RED:WARN);c.drawCircle(cx+(float)Math.cos(aa)*rr,cy+(float)Math.sin(aa)*rr,8+v/4,p);}p.setColor(Color.WHITE);p.setTextSize(24);c.drawText("RADAR SWEEP 360°",30,40,p);invalidate();}}
    class GLSurface extends GLSurfaceView{GLSurface(Context c){super(c);setEGLContextClientVersion(2);setRenderer(new R());setRenderMode(GLSurfaceView.RENDERMODE_CONTINUOUSLY);}class R implements Renderer{FloatBuffer buf;float rot;public void onSurfaceCreated(javax.microedition.khronos.opengles.GL10 gl, javax.microedition.khronos.egl.EGLConfig cfg){GLES20.glClearColor(0.03f,0.07f,0.12f,1);}public void onSurfaceChanged(javax.microedition.khronos.opengles.GL10 gl,int w,int h){GLES20.glViewport(0,0,w,h);}public void onDrawFrame(javax.microedition.khronos.opengles.GL10 gl){GLES20.glClear(GLES20.GL_COLOR_BUFFER_BIT|GLES20.GL_DEPTH_BUFFER_BIT);}}}
}
