package com.arkeomag.pro;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.hardware.*;import android.media.*;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity implements SensorEventListener{
    final int BLUE=Color.rgb(0,122,221), BG=Color.rgb(6,12,22), PANEL=Color.rgb(18,24,35), LINE=Color.rgb(55,72,96);
    LinearLayout root,bar,content; SensorManager sm; Sensor mag; float x,y,z,total,base,anom; ToneGenerator tone; Graph graph; Star3DView star3d;
    String screen="menu";

    public void onCreate(Bundle b){super.onCreate(b); tone=new ToneGenerator(AudioManager.STREAM_MUSIC,70); sm=(SensorManager)getSystemService(SENSOR_SERVICE); mag=sm.getDefaultSensor(Sensor.TYPE_MAGNETIC_FIELD); buildBase(); showMenu();}
    public void onResume(){super.onResume(); if(mag!=null)sm.registerListener(this,mag,SensorManager.SENSOR_DELAY_GAME);} public void onPause(){super.onPause();sm.unregisterListener(this);}    
    void buildBase(){ root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG); setContentView(root); top("Ana Menü"); content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(12,12,12,12);root.addView(content,new LinearLayout.LayoutParams(-1,0,1)); }
    void top(String title){ if(bar!=null)root.removeView(bar); bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(12,0,8,0);bar.setBackgroundColor(BLUE); TextView back=txt("‹",34,Color.WHITE,true);back.setOnClickListener(v->goBack()); bar.addView(back,new LinearLayout.LayoutParams(48,58)); TextView t=txt(title,20,Color.WHITE,true);bar.addView(t,new LinearLayout.LayoutParams(0,58,1)); TextView more=txt("⋮",30,Color.WHITE,true);bar.addView(more,new LinearLayout.LayoutParams(45,58)); root.addView(bar,0); }
    void clear(String title){screen=title;top(title);content.removeAllViews();}
    TextView txt(String s,int sp,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);v.setGravity(Gravity.CENTER_VERTICAL);if(b)v.setTypeface(Typeface.DEFAULT_BOLD);return v;}
    TextView info(String s){TextView v=txt(s,15,Color.LTGRAY,false);v.setPadding(8,8,8,8);return v;}
    GradientDrawable bg(int color,int rad){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(rad);g.setStroke(1,Color.argb(120,120,155,190));return g;}
    ImageView img(int res){ImageView iv=new ImageView(this);iv.setImageResource(res);iv.setAdjustViewBounds(true);iv.setScaleType(ImageView.ScaleType.CENTER_INSIDE);return iv;}
    Button action(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackground(bg(BLUE,8));return b;}

    void showMenu(){clear("Ana Menü"); content.setPadding(10,10,10,10); GridLayout grid=new GridLayout(this);grid.setColumnCount(2);content.addView(grid,new LinearLayout.LayoutParams(-1,-2)); addMenu(grid,"Ground Scan","",R.drawable.menu_groundscan,()->showGround()); addMenu(grid,"Magnetometer","",R.drawable.menu_magnetometer,()->showMagnetometer()); addMenu(grid,"Discrimination","",R.drawable.menu_discrimination,()->showDiscrimination()); addMenu(grid,"3D / 4D V3D","",R.drawable.v3d,()->showV3D()); addMenu(grid,"File Explorer","",R.drawable.ic_menu_archive,()->showFiles()); addMenu(grid,"Settings","",R.drawable.menu_language,()->showSettings()); }
    void addMenu(GridLayout grid,String title,String sub,int icon,final Runnable r){ LinearLayout cell=new LinearLayout(this);cell.setOrientation(LinearLayout.HORIZONTAL);cell.setGravity(Gravity.CENTER_VERTICAL);cell.setPadding(12,10,12,10);cell.setBackground(bg(PANEL,8)); ImageView iv=img(icon);cell.addView(iv,new LinearLayout.LayoutParams(58,58)); LinearLayout texts=new LinearLayout(this);texts.setOrientation(LinearLayout.VERTICAL);texts.setPadding(12,0,0,0);texts.addView(txt(title,16,Color.WHITE,true));texts.addView(txt(sub,12,Color.LTGRAY,false));cell.addView(texts,new LinearLayout.LayoutParams(0,-1,1));cell.setOnClickListener(v->r.run());GridLayout.LayoutParams lp=new GridLayout.LayoutParams();lp.width=getResources().getDisplayMetrics().widthPixels/2-22;lp.height=92;lp.setMargins(5,6,5,6);grid.addView(cell,lp);}

    void showGround(){clear("Ground Scan"); content.addView(statPanel()); graph=new Graph(this,true);content.addView(graph,new LinearLayout.LayoutParams(-1,210)); Heat heat=new Heat(this);content.addView(heat,new LinearLayout.LayoutParams(-1,360)); LinearLayout row=new LinearLayout(this);row.setPadding(0,10,0,0); row.addView(action("Start"),new LinearLayout.LayoutParams(0,70,1));row.addView(action("Transform"),new LinearLayout.LayoutParams(0,70,1));row.addView(action("V3D"),new LinearLayout.LayoutParams(0,70,1));content.addView(row); }
    void showMagnetometer(){clear("Magnetometer");content.addView(statPanel()); Gauge g=new Gauge(this);content.addView(g,new LinearLayout.LayoutParams(-1,270)); graph=new Graph(this,false);content.addView(graph,new LinearLayout.LayoutParams(-1,250));Button cal=action("Zero / Calibrate");cal.setOnClickListener(v->{base=total;Toast.makeText(this,"Taban alındı",0).show();});content.addView(cal,new LinearLayout.LayoutParams(-1,80));}
    void showDiscrimination(){clear("Discrimination"); content.addView(info("Metal ayrımı için X/Y/Z dengesi ve anomali imzası gösterilir.")); Bars bars=new Bars(this);content.addView(bars,new LinearLayout.LayoutParams(-1,320)); content.addView(info("Ferrous / Non-ferrous sınıflandırması sensör stabilitesi arttıkça güçlendirilecek."));}
    void showV3D(){clear("V3D / 4D"); star3d=new Star3DView(this);content.addView(star3d,new LinearLayout.LayoutParams(-1,620)); LinearLayout row=new LinearLayout(this);row.addView(iconBtn(R.drawable.move,"Move"),new LinearLayout.LayoutParams(0,72,1));row.addView(iconBtn(R.drawable.zoom_in,"Zoom +"),new LinearLayout.LayoutParams(0,72,1));row.addView(iconBtn(R.drawable.zoom_out,"Zoom -"),new LinearLayout.LayoutParams(0,72,1));row.addView(iconBtn(R.drawable.refresh,"Refresh"),new LinearLayout.LayoutParams(0,72,1));content.addView(row);}
    Button iconBtn(int res,String text){Button b=action(text);b.setCompoundDrawablesWithIntrinsicBounds(res,0,0,0);return b;}
    void showFiles(){clear("File Explorer");content.addView(info("CSV / V3D kayıt ekranı. Yeni Android sürümlerinde uygulama içi güvenli klasöre kayıt yapılır."));content.addView(action("Save Scan"),new LinearLayout.LayoutParams(-1,80));content.addView(action("Open Last Scan"),new LinearLayout.LayoutParams(-1,80));}
    void showSettings(){clear("Settings");content.addView(info("Language / Sensor / View / Sound ayarları"));CheckBox cb=new CheckBox(this);cb.setText("Sound alarm");cb.setTextColor(Color.WHITE);cb.setChecked(true);content.addView(cb);SeekBar seek=new SeekBar(this);seek.setMax(100);seek.setProgress(45);content.addView(seek,new LinearLayout.LayoutParams(-1,90));}
    View statPanel(){TextView v=txt("X 0.0   Y 0.0   Z 0.0   |B| 0.0   Δ 0.0",15,Color.WHITE,false);v.setPadding(12,10,12,10);v.setBackground(bg(Color.rgb(12,20,32),8));return v;}

    public void onSensorChanged(SensorEvent e){x=e.values[0];y=e.values[1];z=e.values[2];total=(float)Math.sqrt(x*x+y*y+z*z); if(base==0)base=total; anom=Math.abs(total-base); if(graph!=null)graph.add(total,anom); if(star3d!=null)star3d.add(anom); if(anom>25)tone.startTone(ToneGenerator.TONE_PROP_BEEP,60);} public void onAccuracyChanged(Sensor s,int a){}
    void goBack(){ if(!"Ana Menü".equals(screen))showMenu(); else finish(); }
    @Override public void onBackPressed(){goBack();}

    public static class Graph extends View{Paint p=new Paint(1);ArrayList<Float>a=new ArrayList<>(),d=new ArrayList<>();boolean blue;Graph(Context c,boolean b){super(c);blue=b;}void add(float x,float y){a.add(x);d.add(y);while(a.size()>160)a.remove(0);while(d.size()>160)d.remove(0);invalidate();}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();p.setColor(Color.rgb(13,22,35));p.setStyle(Paint.Style.FILL);c.drawRect(0,0,w,h,p);p.setColor(Color.argb(70,255,255,255));p.setStrokeWidth(1);for(int i=1;i<5;i++)c.drawLine(0,h*i/5,w,h*i/5,p);draw(c,a,Color.rgb(0,190,255));draw(c,d,Color.rgb(255,220,0));}void draw(Canvas c,ArrayList<Float>x,int col){if(x.size()<2)return;float max=Collections.max(x),min=Collections.min(x);if(max-min<1){max+=1;min-=1;}Path path=new Path();for(int i=0;i<x.size();i++){float px=i*getWidth()/160f,py=getHeight()-((x.get(i)-min)/(max-min))*(getHeight()-25)-12;if(i==0)path.moveTo(px,py);else path.lineTo(px,py);}p.setColor(col);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(4);c.drawPath(path,p);}}
    public static class Heat extends View{Paint p=new Paint(1);Random r=new Random(1);Heat(Context c){super(c);}int heat(float v){return v<.25?Color.BLUE:v<.5?Color.CYAN:v<.75?Color.YELLOW:Color.RED;}protected void onDraw(Canvas c){int cols=12,rows=10,w=getWidth(),h=getHeight();for(int y=0;y<rows;y++)for(int x=0;x<cols;x++){float v=(float)(Math.sin(x*.8)+Math.cos(y*.7)+2)/4f;p.setColor(heat(v));c.drawRect(x*w/cols,y*h/rows,(x+1)*w/cols,(y+1)*h/rows,p);}}}
    public class Gauge extends View{Paint p=new Paint(1);Gauge(Context c){super(c);}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(28);p.setColor(Color.DKGRAY);c.drawArc(70,35,w-70,h*2-80,200,140,false,p);p.setColor(anom>25?Color.RED:anom>12?Color.YELLOW:Color.CYAN);c.drawArc(70,35,w-70,h*2-80,200,Math.min(140,anom*4),false,p);p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);p.setTextSize(48);p.setColor(Color.WHITE);c.drawText(String.format(Locale.US,"%.1f µT",anom),w/2,h/2,p);invalidate();}}
    public class Bars extends View{Paint p=new Paint(1);Bars(Context c){super(c);}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();float[] vals={x,y,z,total};int[] colors={Color.CYAN,Color.GREEN,Color.YELLOW,Color.RED};String[] names={"X","Y","Z","|B|"};for(int i=0;i<4;i++){float bh=Math.min(h-60,Math.abs(vals[i])*4);p.setColor(colors[i]);c.drawRect(40+i*w/4,h-bh-35,40+i*w/4+55,h-35,p);p.setColor(Color.WHITE);p.setTextSize(22);c.drawText(names[i],48+i*w/4,h-8,p);}invalidate();}}
    public class Star3DView extends View{Paint p=new Paint(1);float rot,phase;ArrayList<Float>f=new ArrayList<>();Star3DView(Context c){super(c);}void add(float v){f.add(v);while(f.size()>200)f.remove(0);phase+=.03f;invalidate();}int heat(float v){v=Math.max(0,Math.min(1,v));return v<.2?Color.rgb(0,20,180):v<.4?Color.CYAN:v<.6?Color.GREEN:v<.8?Color.YELLOW:Color.RED;}float sx(float x,float y,float z,int w,int h){float a=(float)Math.cos(rot),b=(float)Math.sin(rot),xr=(x-50)*a-(y-50)*b,yr=(x-50)*b+(y-50)*a;return w*.5f+xr*4+yr*1.5f;}float sy(float x,float y,float z,int w,int h){float a=(float)Math.cos(rot),b=(float)Math.sin(rot),yr=(x-50)*b+(y-50)*a;return h*.62f+yr*.9f-z*2.1f;}float z(float x,float y){return (float)(45*Math.exp(-Math.pow((x-75)/14,2)-Math.pow((y-60)/18,2))-45*Math.exp(-Math.pow((x-45)/20,2)-Math.pow((y-45)/20,2))+20*Math.sin(x*.1+phase));}protected void onDraw(Canvas c){int w=getWidth(),h=getHeight();p.setColor(Color.rgb(4,8,14));p.setStyle(Paint.Style.FILL);c.drawRect(0,0,w,h,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);p.setColor(Color.WHITE);float[][] q={{0,0,-25},{100,0,-25},{100,100,-25},{0,100,-25},{0,0,85},{100,0,85},{100,100,85},{0,100,85}};int[][] e={{0,1},{1,2},{2,3},{3,0},{4,5},{5,6},{6,7},{7,4},{0,4},{1,5},{2,6},{3,7}};for(int[] m:e)c.drawLine(sx(q[m[0]][0],q[m[0]][1],q[m[0]][2],w,h),sy(q[m[0]][0],q[m[0]][1],q[m[0]][2],w,h),sx(q[m[1]][0],q[m[1]][1],q[m[1]][2],w,h),sy(q[m[1]][0],q[m[1]][1],q[m[1]][2],w,h),p);p.setStyle(Paint.Style.FILL);for(int yy=0;yy<95;yy+=5)for(int xx=0;xx<100;xx+=5){float z1=z(xx,yy),z2=z(xx+5,yy),z3=z(xx+5,yy+5),z4=z(xx,yy+5);Path path=new Path();path.moveTo(sx(xx,yy,z1,w,h),sy(xx,yy,z1,w,h));path.lineTo(sx(xx+5,yy,z2,w,h),sy(xx+5,yy,z2,w,h));path.lineTo(sx(xx+5,yy+5,z3,w,h),sy(xx+5,yy+5,z3,w,h));path.lineTo(sx(xx,yy+5,z4,w,h),sy(xx,yy+5,z4,w,h));path.close();p.setColor(heat(((z1+z2+z3+z4)/4+100)/200));c.drawPath(path,p);}float cx=sx(52,54,55,w,h),cy=sy(52,54,55,w,h);p.setShader(new RadialGradient(cx-30,cy-40,130,Color.CYAN,Color.rgb(0,60,180),Shader.TileMode.CLAMP));c.drawOval(new RectF(cx-90,cy-120,cx+95,cy+95),p);p.setShader(null);p.setColor(Color.WHITE);p.setTextSize(20);c.drawText("V3D / 4D Surface",24,h-24,p);rot+=.002f;phase+=.01f;invalidate();}public boolean onTouchEvent(MotionEvent e){if(e.getAction()==MotionEvent.ACTION_MOVE){rot+=e.getX()/getWidth()*.02f;invalidate();}return true;}}
}
