package com.arkeomag.pro;

import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.location.*;import android.bluetooth.*;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;
import com.lugatek.thubanlodestar.widgets.*;import com.lugatek.thubanlodestar.widgets.opengl.*;

public class MainActivity extends Activity implements SensorHub.Listener{
 SensorHub hub; LinearLayout root,content,nav; TextView header, status, values; LineGraphView line; ColumnGraphView col; ModelSurfaceView model; GaugeCalibration gauge; ArrayList<String> csv=new ArrayList<>(); int screen=0;
 String[] tabs={"Menü","Dedektör","Kalibrasyon","Live","Area","Sonar","BT"};
 public void onCreate(Bundle b){super.onCreate(b); hub=new SensorHub(this); hub.add(this); if(Build.VERSION.SDK_INT>=23)requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.BLUETOOTH_SCAN,Manifest.permission.BLUETOOTH_CONNECT},5); build(); showMenu();}
 public void onResume(){super.onResume();hub.start();} public void onPause(){super.onPause();hub.stop();}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Utils.bg); header=Utils.title(this,"ArkeoMag Pro Classic");status=Utils.tv(this,"No Login • Native Sensor • Classic UI",13,Utils.muted);root.addView(header);root.addView(status);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);nav.setOrientation(LinearLayout.HORIZONTAL);root.addView(nav,new LinearLayout.LayoutParams(-1,58));for(int i=0;i<tabs.length;i++){final int k=i;Button b=Utils.btn(this,tabs[i]);b.setTextSize(11);b.setOnClickListener(v->{screen=k;switch(k){case 0:showMenu();break;case 1:showDetector();break;case 2:showCalibration();break;case 3:showLive();break;case 4:showArea();break;case 5:showSonar();break;case 6:showBluetooth();break;}});nav.addView(b,new LinearLayout.LayoutParams(0,-1,1));}setContentView(root);} 
 void clear(){content.removeAllViews();}
 void showMenu(){clear();content.addView(Utils.title(this,"Ana Menü"));String[] items={"Dedektör","Kalibrasyon","Live Scan","Area Scan","Sonar / 3D","Bluetooth"};for(int i=0;i<items.length;i++){final int k=i+1;Button b=Utils.btn(this,items[i]);b.setTextSize(18);b.setOnClickListener(v->{screen=k; if(k==1)showDetector();else if(k==2)showCalibration();else if(k==3)showLive();else if(k==4)showArea();else if(k==5)showSonar();else showBluetooth();});content.addView(b,new LinearLayout.LayoutParams(-1,70));}content.addView(Utils.tv(this,"Bu sürüm eski APK görünümünün temiz no-login portudur. Firebase / lisans / kullanıcı girişi yoktur.",14,Utils.muted));}
 void showDetector(){clear();content.addView(Utils.title(this,"Dedektör"));col=new ColumnGraphView(this);line=new LineGraphView(this);model=new ModelSurfaceView(this);values=Utils.tv(this,"Bekleniyor...",16,Utils.txt);SeekBar th=new SeekBar(this);th.setMax(60);th.setProgress((int)hub.threshold);th.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean f){hub.threshold=Math.max(1,p);}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});Button zero=Utils.btn(this,"Taban Değeri Sıfırla / Noise Calculate");zero.setOnClickListener(v->hub.zero());content.addView(col,new LinearLayout.LayoutParams(-1,150));content.addView(line,new LinearLayout.LayoutParams(-1,150));content.addView(model,new LinearLayout.LayoutParams(-1,0,1));content.addView(values);content.addView(th,new LinearLayout.LayoutParams(-1,55));content.addView(zero,new LinearLayout.LayoutParams(-1,60));}
 void showCalibration(){clear();content.addView(Utils.title(this,"Kalibrasyon"));gauge=new GaugeCalibration(this);content.addView(gauge,new LinearLayout.LayoutParams(-1,330));content.addView(Utils.tv(this,"Telefonu 8 çizerek döndür. Hard-iron offset için tüm eksenlerde veri toplanır.",15,Utils.txt));Button zero=Utils.btn(this,"Kalibrasyonu Sıfırla");zero.setOnClickListener(v->hub.zero());content.addView(zero,new LinearLayout.LayoutParams(-1,65));}
 void showLive(){clear();content.addView(Utils.title(this,"Live Scan"));line=new LineGraphView(this);model=new ModelSurfaceView(this);values=Utils.tv(this,"Canlı tarama",16,Utils.txt);Button save=Utils.btn(this,"CSV Nokta Kaydet");save.setOnClickListener(v->savePoint());content.addView(line,new LinearLayout.LayoutParams(-1,160));content.addView(model,new LinearLayout.LayoutParams(-1,0,1));content.addView(values);content.addView(save,new LinearLayout.LayoutParams(-1,65));}
 void showArea(){clear();content.addView(Utils.title(this,"Area Scan"));model=new ModelSurfaceView(this);values=Utils.tv(this,"Grid/alan görünümü - v2 temel",16,Utils.txt);Button save=Utils.btn(this,"Nokta Kaydet");save.setOnClickListener(v->savePoint());content.addView(model,new LinearLayout.LayoutParams(-1,0,1));content.addView(values);content.addView(save,new LinearLayout.LayoutParams(-1,65));}
 void showSonar(){clear();content.addView(Utils.title(this,"Sonar / 3D"));line=new LineGraphView(this);model=new ModelSurfaceView(this);content.addView(line,new LinearLayout.LayoutParams(-1,155));content.addView(model,new LinearLayout.LayoutParams(-1,0,1));content.addView(Utils.tv(this,"Shader/model assetleri app/src/main/assets içinde taşındı.",14,Utils.muted));}
 void showBluetooth(){clear();content.addView(Utils.title(this,"Bluetooth"));TextView list=Utils.tv(this,"Cihazlar listeleniyor...",15,Utils.txt);content.addView(list,new LinearLayout.LayoutParams(-1,-2));try{BluetoothAdapter ba=BluetoothAdapter.getDefaultAdapter();StringBuilder sb=new StringBuilder();if(ba==null)sb.append("Bluetooth yok");else{if(Build.VERSION.SDK_INT>=31&&checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED)sb.append("BLUETOOTH_CONNECT izni gerekli");else for(BluetoothDevice d:ba.getBondedDevices())sb.append(d.getName()).append("\n").append(d.getAddress()).append("\n\n");}list.setText(sb.toString());}catch(Exception e){list.setText(e.toString());}}
 void savePoint(){csv.add(System.currentTimeMillis()+","+hub.mag[0]+","+hub.mag[1]+","+hub.mag[2]+","+hub.total+","+hub.delta);try{File f=new File(getExternalFilesDir(null),"arkeomag_scan.csv");FileWriter fw=new FileWriter(f);fw.write("t,x,y,z,total,delta\n");for(String s:csv)fw.write(s+"\n");fw.close();Toast.makeText(this,"Kaydedildi: "+f.getAbsolutePath(),Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,e.toString(),Toast.LENGTH_LONG).show();}}
 public void onSensor(float[] m,float[] a,float[] g,float total,float delta){String s=String.format(Locale.US,"X %.2f  Y %.2f  Z %.2f  |B| %.2f µT  Sapma %.2f µT",m[0],m[1],m[2],total,delta);runOnUiThread(()->{status.setText(s);if(values!=null)values.setText(s);if(line!=null)line.add(delta);if(col!=null)col.add(delta);if(model!=null)model.setLevel(delta);if(gauge!=null)gauge.setQuality(Math.min(1,delta/35f));});}
}
